using JuvicClinic.Api.Data; using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore;
namespace JuvicClinic.Api.Features.Inventory;
[Authorize(Roles="ADMIN,DOCTOR,NURSE,CASHIER"),ApiController,Route("api/inventory")]
public sealed class InventoryController(ClinicDbContext db):ControllerBase{[HttpGet("movements")]public async Task<object>Movements(Guid? medicineId,string? type,DateTime? from,DateTime? to,int page=1,int pageSize=30,CancellationToken ct=default){var q=db.StockTransactions.AsNoTracking().AsQueryable();if(medicineId is not null)q=q.Where(x=>x.MedicineId==medicineId);if(!string.IsNullOrWhiteSpace(type)&&Enum.TryParse<Domain.MovementType>(type,true,out var movement))q=q.Where(x=>x.Type==movement);if(from is not null)q=q.Where(x=>x.CreatedAt>=from.Value.ToUniversalTime());if(to is not null)q=q.Where(x=>x.CreatedAt<=to.Value.ToUniversalTime());var total=await q.CountAsync(ct);var data=await q.OrderByDescending(x=>x.CreatedAt).Skip((Math.Max(page,1)-1)*Math.Clamp(pageSize,1,100)).Take(Math.Clamp(pageSize,1,100)).Select(x=>new{x.Id,x.MedicineId,medicine=db.Medicines.Where(m=>m.Id==x.MedicineId).Select(m=>m.Name+" "+m.Strength).FirstOrDefault(),x.MedicineBatchId,batchNumber=db.MedicineBatches.Where(b=>b.Id==x.MedicineBatchId).Select(b=>b.BatchNumber).FirstOrDefault(),x.Type,x.QuantityChange,x.BalanceAfter,x.Reason,x.ReferenceType,x.ReferenceId,x.CreatedAt}).ToListAsync(ct);return new{data,total,page,pageSize};}}

[Authorize(Roles="ADMIN,DOCTOR,NURSE,CASHIER"),ApiController,Route("api/inventory/batches")]
public sealed class InventoryBatchesController(ClinicDbContext db):ControllerBase
{
 [HttpGet]public async Task<object>List(string? search,string status="all",int page=1,int pageSize=30,CancellationToken ct=default){var today=DateOnly.FromDateTime(DateTime.UtcNow);var warning=today.AddDays(90);var q=db.MedicineBatches.AsNoTracking().AsQueryable();if(!string.IsNullOrWhiteSpace(search)){var s=search.Trim().ToLower();q=q.Where(x=>x.Medicine.Name.ToLower().Contains(s)||(x.Medicine.Strength!=null&&x.Medicine.Strength.ToLower().Contains(s))||(x.BatchNumber!=null&&x.BatchNumber.ToLower().Contains(s))||(x.Supplier!=null&&x.Supplier.ToLower().Contains(s)));}q=status.ToLowerInvariant() switch{"available"=>q.Where(x=>x.IsActive&&x.QuantityRemaining>0&&(x.ExpiryDate==null||x.ExpiryDate>today)),"expired"=>q.Where(x=>x.ExpiryDate!=null&&x.ExpiryDate<=today),"expiring"=>q.Where(x=>x.ExpiryDate!=null&&x.ExpiryDate>today&&x.ExpiryDate<=warning),"empty"=>q.Where(x=>x.QuantityRemaining<=0),_=>q};var total=await q.CountAsync(ct);var size=Math.Clamp(pageSize,1,100);var data=await q.OrderBy(x=>x.ExpiryDate==null).ThenBy(x=>x.ExpiryDate).ThenBy(x=>x.Medicine.Name).Skip((Math.Max(page,1)-1)*size).Take(size).Select(x=>new{x.Id,x.MedicineId,medicine=new{x.Medicine.Id,x.Medicine.Name,x.Medicine.Strength,x.Medicine.Form,x.Medicine.Unit,x.Medicine.ImageUrl},x.BatchNumber,x.Supplier,x.QuantityReceived,x.QuantityRemaining,x.UnitCost,x.SellingPrice,x.ExpiryDate,x.ReceivedAt,x.IsActive,stockValue=x.QuantityRemaining*x.UnitCost,potentialRevenue=x.QuantityRemaining*x.SellingPrice}).ToListAsync(ct);return new{data,total,page=Math.Max(page,1),pageSize=size};}
}
