import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { LogOut, PlayCircle, ShieldAlert } from 'lucide-react';
import { useState } from 'react';
import { useParams } from 'react-router-dom';
import { toast } from 'sonner';
import { api } from '../../shared/services/api';
import { useAuth } from '../auth/auth';
import PatientDetailPage from './PatientDetailPage';

type Action = 'start' | 'safety' | 'discharge' | null;

export default function PatientWorkflowPage() {
  const { id } = useParams(); const { user } = useAuth(); const qc = useQueryClient();
  const [action, setAction] = useState<Action>(null); const [careType, setCareType] = useState('OUTPATIENT'); const [reason, setReason] = useState('');
  const [summary, setSummary] = useState(''); const [cancelDoses, setCancelDoses] = useState(false);
  const patient = useQuery({ queryKey: ['patient', id], queryFn: async () => (await api.get(`/patients/${id}`)).data });
  const refresh = async () => { await qc.invalidateQueries({ queryKey: ['patient', id] }); await qc.invalidateQueries({ queryKey: ['patients'] }); await qc.invalidateQueries({ queryKey: ['due-treatments'] }); };
  const start = useMutation({ mutationFn: () => api.post(`/patients/${id}/visits`, { careType, reason }), onSuccess: async () => { toast.success('New visit started. Previous visits remain in history.'); setAction(null); setReason(''); await refresh(); }, onError: errorToast });
  const safety = useMutation({ mutationFn: (data: any) => api.patch(`/patients/${id}/safety`, data), onSuccess: async () => { toast.success('Medical safety record updated.'); setAction(null); await refresh(); }, onError: errorToast });
  const discharge = useMutation({ mutationFn: () => api.post(`/patients/visits/${patient.data.currentVisit.id}/discharge`, { summary, cancelOutstandingDoses: cancelDoses }), onSuccess: async () => { toast.success('Patient discharged; visit history and outstanding bill were preserved.'); setAction(null); setSummary(''); await refresh(); }, onError: errorToast });
  const canDischarge = user?.role === 'ADMIN' || user?.role === 'DOCTOR';
  const p = patient.data;
  return <div className="space-y-4">
    {p && <section className="card border-l-4 border-l-amber-500"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><ShieldAlert className="text-amber-600" size={20} /><h2 className="font-bold">Medical safety and visit control</h2></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-4"><Safety label="Blood group" value={p.bloodGroup} /><Safety label="Allergies" value={p.allergies} warning /><Safety label="Conditions" value={p.medicalConditions} warning /><Safety label="Current medicines" value={p.currentMedication} warning /></div></div><div className="flex shrink-0 flex-wrap gap-2"><button className="rounded-xl border bg-white px-4 py-2 font-semibold" onClick={() => setAction('safety')}>Update safety record</button>{!p.currentVisit && <button className="btn-primary" onClick={() => setAction('start')}><PlayCircle size={17} />Start new visit</button>}{p.currentVisit && canDischarge && <button className="inline-flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2 font-semibold text-white" onClick={() => setAction('discharge')}><LogOut size={17} />Discharge</button>}</div></div></section>}
    {action === 'start' && <ActionForm title="Start a returning-patient visit" busy={start.isPending} submit={() => start.mutate()} close={() => setAction(null)}><label className="block text-sm">Care type<select className="input mt-1" value={careType} onChange={e => setCareType(e.target.value)}><option value="OUTPATIENT">Outpatient</option><option value="INPATIENT">Inpatient</option></select></label><label className="mt-3 block text-sm">Reason for visit<textarea required className="input mt-1 min-h-24" value={reason} onChange={e => setReason(e.target.value)} /></label></ActionForm>}
    {action === 'safety' && <SafetyForm patient={p} busy={safety.isPending} submit={data => safety.mutate(data)} close={() => setAction(null)} />}
    {action === 'discharge' && <ActionForm title="Complete and discharge this visit" busy={discharge.isPending} submit={() => discharge.mutate()} close={() => setAction(null)}><label className="block text-sm">Discharge summary<textarea required className="input mt-1 min-h-28" value={summary} onChange={e => setSummary(e.target.value)} placeholder="Condition at discharge, advice and follow-up" /></label><label className="mt-3 flex items-start gap-2 rounded-xl bg-amber-50 p-3 text-sm"><input className="mt-1" type="checkbox" checked={cancelDoses} onChange={e => setCancelDoses(e.target.checked)} /><span>Cancel any remaining scheduled doses. Leave unchecked to make the system block discharge if treatment is still due.</span></label></ActionForm>}
    <PatientDetailPage />
  </div>;
}

function Safety({ label, value, warning }: { label: string; value?: string; warning?: boolean }) { return <div className={`rounded-xl p-3 ${warning && value ? 'bg-red-50 text-red-800' : 'bg-slate-50'}`}><p className="text-xs font-semibold uppercase opacity-70">{label}</p><p>{value || 'None recorded'}</p></div>; }
function ActionForm({ title, busy, submit, close, children }: { title: string; busy: boolean; submit: () => void; close: () => void; children: React.ReactNode }) { return <form className="card border-brand-100" onSubmit={e => { e.preventDefault(); submit(); }}><h2 className="mb-4 text-lg font-bold">{title}</h2>{children}<div className="mt-4 flex justify-end gap-2"><button type="button" className="rounded-xl border px-4 py-2" onClick={close}>Cancel</button><button className="btn-primary" disabled={busy}>{busy ? 'Saving…' : 'Confirm'}</button></div></form>; }
function SafetyForm({ patient, busy, submit, close }: { patient: any; busy: boolean; submit: (data: any) => void; close: () => void }) { const [data, setData] = useState({ bloodGroup: patient?.bloodGroup ?? '', allergies: patient?.allergies ?? '', medicalConditions: patient?.medicalConditions ?? '', currentMedication: patient?.currentMedication ?? '' }); const field = (key: keyof typeof data) => ({ value: data[key], onChange: (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => setData(v => ({ ...v, [key]: e.target.value })) }); return <ActionForm title="Update medical safety record" busy={busy} submit={() => submit(data)} close={close}><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Blood group<select className="input mt-1" {...field('bloodGroup')}><option value="">Not recorded</option>{['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'].map(x => <option key={x}>{x}</option>)}</select></label><label className="text-sm">Allergies<textarea className="input mt-1 min-h-24" {...field('allergies')} /></label><label className="text-sm">Medical conditions<textarea className="input mt-1 min-h-24" {...field('medicalConditions')} /></label><label className="text-sm">Current medicines<textarea className="input mt-1 min-h-24" {...field('currentMedication')} /></label></div></ActionForm>; }
function errorToast(e: any) { toast.error(e.response?.data?.message ?? 'The action could not be completed.'); }
