namespace ClinicManagement.Api.Domain;

public enum StaffRole { ADMIN, DOCTOR, NURSE, CASHIER }
public enum CareType { OUTPATIENT, INPATIENT }
public enum VisitStatus { OPEN, ACTIVE, COMPLETED, CANCELLED }
public enum DoseStatus { SCHEDULED, GIVEN, LATE, MISSED, CANCELLED }
public enum MovementType { PURCHASE, SALE, TREATMENT, ADJUSTMENT, RETURN }
public enum PaymentMethod { CASH, MOBILE_MONEY, BANK_TRANSFER, CARD, OTHER }

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedAt { get; set; } = DateTime.UtcNow; public DateTime UpdatedAt { get; set; } = DateTime.UtcNow; }
public sealed class ClinicSetting : Entity { public string ClinicName { get; set; } = "Medical Clinic"; public string ShortName { get; set; } = "Clinic"; public string? LogoUrl { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Address { get; set; } public string Currency { get; set; } = "UGX"; public string Timezone { get; set; } = "Africa/Kampala"; public string? PrimaryContact { get; set; } public string? ReceiptFooter { get; set; } public bool IsActive { get; set; } = true; }
public sealed class Role : Entity { public StaffRole Name { get; set; } public ICollection<User> Users { get; set; } = []; }
public sealed class User : Entity { public Guid RoleId { get; set; } public Role Role { get; set; } = null!; public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string? Phone { get; set; } public string Email { get; set; } = ""; public string PasswordHash { get; set; } = ""; public bool IsActive { get; set; } = true; public DateTime? LastLoginAt { get; set; } }
public sealed class Patient : Entity { public string PatientNumber { get; set; } = ""; public string FirstName { get; set; } = ""; public string? MiddleName { get; set; } public string LastName { get; set; } = ""; public DateOnly DateOfBirth { get; set; } public string Sex { get; set; } = ""; public string PrimaryPhone { get; set; } = ""; public string? AlternativePhone { get; set; } public string? Email { get; set; } public string Address { get; set; } = ""; public string? Nin { get; set; } public string? Occupation { get; set; } public string? BloodGroup { get; set; } public bool IsActive { get; set; } = true; public ICollection<NextOfKin> NextOfKin { get; set; } = []; public ICollection<Visit> Visits { get; set; } = []; }
public sealed class NextOfKin : Entity { public Guid PatientId { get; set; } public Patient Patient { get; set; } = null!; public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string Relationship { get; set; } = ""; public string Phone { get; set; } = ""; public string? AlternativePhone { get; set; } public string? Address { get; set; } public bool IsPrimary { get; set; } }
public sealed class Visit : Entity { public string VisitNumber { get; set; } = ""; public Guid PatientId { get; set; } public Patient Patient { get; set; } = null!; public Guid? PreviousVisitId { get; set; } public Visit? PreviousVisit { get; set; } public CareType CareType { get; set; } public VisitStatus Status { get; set; } = VisitStatus.OPEN; public string Reason { get; set; } = ""; public DateTime StartedAt { get; set; } = DateTime.UtcNow; public DateTime? ClosedAt { get; set; } public Guid CreatedById { get; set; } public ICollection<Assessment> Assessments { get; set; } = []; public ICollection<Diagnosis> Diagnoses { get; set; } = []; public ICollection<TreatmentPlan> TreatmentPlans { get; set; } = []; }
public sealed class Assessment : Entity { public Guid VisitId { get; set; } public Visit Visit { get; set; } = null!; public decimal? Temperature { get; set; } public int? Systolic { get; set; } public int? Diastolic { get; set; } public int? PulseRate { get; set; } public int? RespiratoryRate { get; set; } public decimal? Weight { get; set; } public decimal? Height { get; set; } public string? Notes { get; set; } public Guid RecordedById { get; set; } public DateTime RecordedAt { get; set; } = DateTime.UtcNow; public ICollection<AssessmentObservation> Observations { get; set; } = []; }
public sealed class AssessmentObservation : Entity { public Guid AssessmentId { get; set; } public Assessment Assessment { get; set; } = null!; public string Name { get; set; } = ""; public string Value { get; set; } = ""; public string? Unit { get; set; } public string? Notes { get; set; } }
public sealed class Diagnosis : Entity { public Guid VisitId { get; set; } public Visit Visit { get; set; } = null!; public string Description { get; set; } = ""; public string? Notes { get; set; } public string? EvidenceUrl { get; set; } public string? EvidencePublicId { get; set; } public string? EvidenceMimeType { get; set; } public string? EvidenceOriginalName { get; set; } public Guid DiagnosedById { get; set; } public DateTime DiagnosedAt { get; set; } = DateTime.UtcNow; }
public sealed class Medicine : Entity { public string Name { get; set; } = ""; public string? GenericName { get; set; } public string? Strength { get; set; } public string Form { get; set; } = "OTHER"; public string Unit { get; set; } = "unit"; public decimal MinimumStockLevel { get; set; } public decimal? DefaultSellingPrice { get; set; } public string? ImageUrl { get; set; } public string? ImagePublicId { get; set; } public string? ImageMimeType { get; set; } public bool IsActive { get; set; } = true; public ICollection<MedicineBatch> Batches { get; set; } = []; }
public sealed class MedicineBatch : Entity { public Guid MedicineId { get; set; } public Medicine Medicine { get; set; } = null!; public string? BatchNumber { get; set; } public string? Supplier { get; set; } public decimal QuantityReceived { get; set; } public decimal QuantityRemaining { get; set; } public decimal UnitCost { get; set; } public decimal SellingPrice { get; set; } public DateOnly? ExpiryDate { get; set; } public DateTime ReceivedAt { get; set; } = DateTime.UtcNow; public Guid ReceivedById { get; set; } public bool IsActive { get; set; } = true; }
public sealed class TreatmentPlan : Entity { public Guid VisitId { get; set; } public Visit Visit { get; set; } = null!; public string Status { get; set; } = "ACTIVE"; public DateTime StartsAt { get; set; } public DateTime? ExpectedEndAt { get; set; } public DateTime? CompletedAt { get; set; } public string? Instructions { get; set; } public Guid CreatedById { get; set; } public ICollection<TreatmentOrder> Orders { get; set; } = []; }
public sealed class TreatmentOrder : Entity { public Guid TreatmentPlanId { get; set; } public TreatmentPlan TreatmentPlan { get; set; } = null!; public string TreatmentName { get; set; } = ""; public Guid? MedicineId { get; set; } public Guid? PreferredBatchId { get; set; } public string? Route { get; set; } public decimal DoseQuantity { get; set; } public int? FrequencyHours { get; set; } public int NumberOfDoses { get; set; } public decimal TotalQuantity { get; set; } public decimal LockedUnitPrice { get; set; } public decimal TotalPrice { get; set; } public string? Instructions { get; set; } public ICollection<TreatmentDose> Doses { get; set; } = []; }
public sealed class TreatmentDose : Entity { public Guid TreatmentOrderId { get; set; } public TreatmentOrder TreatmentOrder { get; set; } = null!; public DateTime ScheduledAt { get; set; } public DoseStatus Status { get; set; } = DoseStatus.SCHEDULED; public DateTime? AdministeredAt { get; set; } public Guid? AdministeredById { get; set; } public Guid? MedicineBatchId { get; set; } public decimal? QuantityUsed { get; set; } public string? Notes { get; set; } }
public sealed class StockTransaction : Entity { public Guid MedicineId { get; set; } public Guid? MedicineBatchId { get; set; } public MovementType Type { get; set; } public decimal QuantityChange { get; set; } public decimal BalanceAfter { get; set; } public string Reason { get; set; } = ""; public string? ReferenceType { get; set; } public Guid? ReferenceId { get; set; } public Guid PerformedById { get; set; } }
public sealed class Bill : Entity { public string BillNumber { get; set; } = ""; public Guid VisitId { get; set; } public decimal OriginalAmount { get; set; } public decimal AdjustmentAmount { get; set; } public decimal TotalAmount { get; set; } public decimal PaidAmount { get; set; } public string Status { get; set; } = "OPEN"; public ICollection<BillItem> Items { get; set; } = []; }
public sealed class BillItem : Entity { public Guid BillId { get; set; } public Bill Bill { get; set; } = null!; public string ItemType { get; set; } = ""; public string Description { get; set; } = ""; public decimal Quantity { get; set; } public decimal UnitPrice { get; set; } public decimal Amount { get; set; } public Guid? SourceId { get; set; } }
public sealed class Payment : Entity { public string ReceiptNumber { get; set; } = ""; public Guid? BillId { get; set; } public decimal Amount { get; set; } public PaymentMethod Method { get; set; } public string? Reference { get; set; } public string? PaymentProofUrl { get; set; } public string? PaymentProofPublicId { get; set; } public string? PaymentProofMimeType { get; set; } public string? PaymentProofOriginalName { get; set; } public string? ReceiptDocumentUrl { get; set; } public string? ReceiptDocumentPublicId { get; set; } public string? ReceiptDocumentMimeType { get; set; } public string? ReceiptDocumentOriginalName { get; set; } public DateTime ReceivedAt { get; set; } = DateTime.UtcNow; public Guid ReceivedById { get; set; } public string Status { get; set; } = "COMPLETED"; }
public sealed class VisitDocument : Entity { public Guid VisitId { get; set; } public Visit Visit { get; set; } = null!; public string DocumentType { get; set; } = "CLINICAL_FORM"; public string Title { get; set; } = ""; public string FileUrl { get; set; } = ""; public string PublicId { get; set; } = ""; public string MimeType { get; set; } = ""; public string OriginalName { get; set; } = ""; public long FileSize { get; set; } public Guid UploadedById { get; set; } }
public sealed class RetailSale : Entity { public string SaleNumber { get; set; } = ""; public decimal TotalCost { get; set; } public decimal TotalAmount { get; set; } public decimal AmountReceived { get; set; } public PaymentMethod PaymentMethod { get; set; } public string? PaymentReference { get; set; } public string? CustomerName { get; set; } public string? CustomerPhone { get; set; } public string? PaymentProofUrl { get; set; } public string? PaymentProofPublicId { get; set; } public string? ReceiptDocumentUrl { get; set; } public string? ReceiptDocumentPublicId { get; set; } public string Status { get; set; } = "COMPLETED"; public DateTime SoldAt { get; set; } = DateTime.UtcNow; public Guid SoldById { get; set; } public ICollection<RetailSaleItem> Items { get; set; } = []; }
public sealed class RetailSaleItem : Entity { public Guid RetailSaleId { get; set; } public RetailSale RetailSale { get; set; } = null!; public Guid MedicineId { get; set; } public Medicine Medicine { get; set; } = null!; public Guid MedicineBatchId { get; set; } public MedicineBatch MedicineBatch { get; set; } = null!; public decimal Quantity { get; set; } public decimal UnitCost { get; set; } public decimal UnitPrice { get; set; } public decimal TotalCost { get; set; } public decimal TotalAmount { get; set; } }
public sealed class Expense : Entity { public string Category { get; set; } = ""; public Guid? PurchaseId { get; set; } public string Description { get; set; } = ""; public decimal Amount { get; set; } public PaymentMethod Method { get; set; } public string? Reference { get; set; } public DateOnly ExpenseDate { get; set; } public Guid RecordedById { get; set; } }
public sealed class AuditLog { public long Id { get; set; } public Guid? UserId { get; set; } public string Action { get; set; } = ""; public string EntityType { get; set; } = ""; public string EntityId { get; set; } = ""; public string? OldValues { get; set; } public string? NewValues { get; set; } public string? IpAddress { get; set; } public DateTime CreatedAt { get; set; } = DateTime.UtcNow; }
